### ISSUE TITLE
Fix outstanding issues from PR #2

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-dualscreen#3]
Follow-up from this PR:
https://github.com/microsoft/react-native-dualscreen/pull/2

There are a number of outstanding comments that need to be addressed.

**Comment by chrisglein** [comment]
It looks like based on the above there was a PR to address these. Addressed in [this commit](https://github.com/microsoft/react-native-dualscreen/commit/172ab7dca3e353abcfb434c3b8fba94805a2bd38). If there are more to extract from that they need to be pulled out and identified.
