### ISSUE TITLE
dualscreenInfo does not work when included as a dependency from another npm package

### ISSUE THREAD

**Issue by keilwastaken** [microsoft/react-native-dualscreen#48]
Example:

for twopane-navigation I included dualscreeninfo as a dependency to be included when published

expected result: after the user sets up their gradle.build file correctly dualscreeninfo should be working in the background for the twopane-navigation library

actual  result; dualscreeninfo stays in onepane mode because no events are trigger ie like the ispanning eventhandler. This means the user has to download dualscreeninfo independent of twopane-navigation for the twopane-navigation library to function properly

**Comment by chrisglein** [comment]
Can you share your RN version information?
Also, can you provide more detail on the repro for this? (if you have a repo you can share that'd be ideal, but share what you can)

> This means the user has to download dualscreeninfo independent of twopane-navigation for the twopane-navigation library to function properly

By that do you mean downloading the package and put it into node_modules manually?
