### ISSUE TITLE
Publish react-native-dualscreeninfo

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-dualscreen#6]
As a starting point we should publish an initial version of react-native-dualscreeninfo manually.

We should also setup the CI loop to have a publish pipeline so that whenever we make changes, the version is bumped and a new version is published to npm.

**Comment by kmelmon** [comment]
@thewulf7 do you have cycles to take this?

**Comment by thewulf7** [comment]
I can do it manually now. For CI - I need more details where to do it :)

**Comment by kmelmon** [comment]
Thanks!  We use an open-source package called beachball for publishing react-native-windows to npm, this might be overkill but could work for this repo too.  Start here: https://github.com/microsoft/react-native-windows/blob/master/.ado/publish.yml
