### ISSUE TITLE
[Feature] No-op for iOS

### ISSUE THREAD

**Issue by luisnaranjo733** [microsoft/react-native-dualscreen#8]
It makes sense that this SDK only works for Android and Windows. There are no dual screen iOS devices today.

But from a developer API niceness perspective, it would be nice if this API worked on iOS in the sense that if I call getIsDualScreen() or something like that, it won't cause a crash because this SDK just returns sensible defaults instead of trying to call native code that isn't there.

**Comment by luisnaranjo733** [comment]
This would allow developers to avoid splitting their code across Android and iOS which is actually really impactful and makes it easier for them to sprinkle in dual screen support here and there without having to modify their entire UI layer just to avoid crashes on iOS

**Comment by kmelmon** [comment]
@luisnaranjo733  where does it crash if you run this on iOS?  We designed the API as you described, so if there's a crash it's just a bug.

**Comment by luisnaranjo733** [comment]
I never actually ran the code, just read the source. I remember at one point I saw a call that I thought would try to call into native iOS code that doesn't exist and subsequently cause a crash.

This was long enough ago that it may have been fixed but if you're already thinking about that that's great! I'll close this issue. Thanks!
